server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: promotionService
    #配置数据源
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
    #type: com.alibaba.druid.pool.DruidDataSource
#mybatis配置
mybatis:
  mapper-locations: classpath*:/mappers/*.xml
  #扫描实体类
  type-aliases-package: com.mr.mall.mall_promotion.entity
  configuration:
    #驼峰转换
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
